# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bryce/Documents/HTTCPP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bryce/Documents/HTTCPP/CPPCrypto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bryce/Documents/HTTCPP/CPPCrypto/CMakeFiles /home/bryce/Documents/HTTCPP/CPPCrypto/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bryce/Documents/HTTCPP/CPPCrypto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HTTCPP

# Build rule for target.
HTTCPP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HTTCPP
.PHONY : HTTCPP

# fast build rule for target.
HTTCPP/fast:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/build
.PHONY : HTTCPP/fast

#=============================================================================
# Target rules for targets named CPPCrypto

# Build rule for target.
CPPCrypto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CPPCrypto
.PHONY : CPPCrypto

# fast build rule for target.
CPPCrypto/fast:
	$(MAKE) -f CPPCrypto/CMakeFiles/CPPCrypto.dir/build.make CPPCrypto/CMakeFiles/CPPCrypto.dir/build
.PHONY : CPPCrypto/fast

src/HTTPClient.o: src/HTTPClient.cpp.o

.PHONY : src/HTTPClient.o

# target to build an object file
src/HTTPClient.cpp.o:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/HTTPClient.cpp.o
.PHONY : src/HTTPClient.cpp.o

src/HTTPClient.i: src/HTTPClient.cpp.i

.PHONY : src/HTTPClient.i

# target to preprocess a source file
src/HTTPClient.cpp.i:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/HTTPClient.cpp.i
.PHONY : src/HTTPClient.cpp.i

src/HTTPClient.s: src/HTTPClient.cpp.s

.PHONY : src/HTTPClient.s

# target to generate assembly for a file
src/HTTPClient.cpp.s:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/HTTPClient.cpp.s
.PHONY : src/HTTPClient.cpp.s

src/HTTPSClient.o: src/HTTPSClient.cpp.o

.PHONY : src/HTTPSClient.o

# target to build an object file
src/HTTPSClient.cpp.o:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/HTTPSClient.cpp.o
.PHONY : src/HTTPSClient.cpp.o

src/HTTPSClient.i: src/HTTPSClient.cpp.i

.PHONY : src/HTTPSClient.i

# target to preprocess a source file
src/HTTPSClient.cpp.i:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/HTTPSClient.cpp.i
.PHONY : src/HTTPSClient.cpp.i

src/HTTPSClient.s: src/HTTPSClient.cpp.s

.PHONY : src/HTTPSClient.s

# target to generate assembly for a file
src/HTTPSClient.cpp.s:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/HTTPSClient.cpp.s
.PHONY : src/HTTPSClient.cpp.s

src/TLS/TLSHandshake.o: src/TLS/TLSHandshake.cpp.o

.PHONY : src/TLS/TLSHandshake.o

# target to build an object file
src/TLS/TLSHandshake.cpp.o:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/TLS/TLSHandshake.cpp.o
.PHONY : src/TLS/TLSHandshake.cpp.o

src/TLS/TLSHandshake.i: src/TLS/TLSHandshake.cpp.i

.PHONY : src/TLS/TLSHandshake.i

# target to preprocess a source file
src/TLS/TLSHandshake.cpp.i:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/TLS/TLSHandshake.cpp.i
.PHONY : src/TLS/TLSHandshake.cpp.i

src/TLS/TLSHandshake.s: src/TLS/TLSHandshake.cpp.s

.PHONY : src/TLS/TLSHandshake.s

# target to generate assembly for a file
src/TLS/TLSHandshake.cpp.s:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/TLS/TLSHandshake.cpp.s
.PHONY : src/TLS/TLSHandshake.cpp.s

src/URL.o: src/URL.cpp.o

.PHONY : src/URL.o

# target to build an object file
src/URL.cpp.o:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/URL.cpp.o
.PHONY : src/URL.cpp.o

src/URL.i: src/URL.cpp.i

.PHONY : src/URL.i

# target to preprocess a source file
src/URL.cpp.i:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/URL.cpp.i
.PHONY : src/URL.cpp.i

src/URL.s: src/URL.cpp.s

.PHONY : src/URL.s

# target to generate assembly for a file
src/URL.cpp.s:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/URL.cpp.s
.PHONY : src/URL.cpp.s

src/linux/TCPClient.o: src/linux/TCPClient.cpp.o

.PHONY : src/linux/TCPClient.o

# target to build an object file
src/linux/TCPClient.cpp.o:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/linux/TCPClient.cpp.o
.PHONY : src/linux/TCPClient.cpp.o

src/linux/TCPClient.i: src/linux/TCPClient.cpp.i

.PHONY : src/linux/TCPClient.i

# target to preprocess a source file
src/linux/TCPClient.cpp.i:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/linux/TCPClient.cpp.i
.PHONY : src/linux/TCPClient.cpp.i

src/linux/TCPClient.s: src/linux/TCPClient.cpp.s

.PHONY : src/linux/TCPClient.s

# target to generate assembly for a file
src/linux/TCPClient.cpp.s:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/linux/TCPClient.cpp.s
.PHONY : src/linux/TCPClient.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/windows/TCPClient.o: src/windows/TCPClient.cpp.o

.PHONY : src/windows/TCPClient.o

# target to build an object file
src/windows/TCPClient.cpp.o:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/windows/TCPClient.cpp.o
.PHONY : src/windows/TCPClient.cpp.o

src/windows/TCPClient.i: src/windows/TCPClient.cpp.i

.PHONY : src/windows/TCPClient.i

# target to preprocess a source file
src/windows/TCPClient.cpp.i:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/windows/TCPClient.cpp.i
.PHONY : src/windows/TCPClient.cpp.i

src/windows/TCPClient.s: src/windows/TCPClient.cpp.s

.PHONY : src/windows/TCPClient.s

# target to generate assembly for a file
src/windows/TCPClient.cpp.s:
	$(MAKE) -f CMakeFiles/HTTCPP.dir/build.make CMakeFiles/HTTCPP.dir/src/windows/TCPClient.cpp.s
.PHONY : src/windows/TCPClient.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... HTTCPP"
	@echo "... CPPCrypto"
	@echo "... src/HTTPClient.o"
	@echo "... src/HTTPClient.i"
	@echo "... src/HTTPClient.s"
	@echo "... src/HTTPSClient.o"
	@echo "... src/HTTPSClient.i"
	@echo "... src/HTTPSClient.s"
	@echo "... src/TLS/TLSHandshake.o"
	@echo "... src/TLS/TLSHandshake.i"
	@echo "... src/TLS/TLSHandshake.s"
	@echo "... src/URL.o"
	@echo "... src/URL.i"
	@echo "... src/URL.s"
	@echo "... src/linux/TCPClient.o"
	@echo "... src/linux/TCPClient.i"
	@echo "... src/linux/TCPClient.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/windows/TCPClient.o"
	@echo "... src/windows/TCPClient.i"
	@echo "... src/windows/TCPClient.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

